server:
  port: 80

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/java220
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


redis:
  host-ip: localhost
  port: 6380
  timeout: 10000
